[package]
name = "knotrel-core"
description = "Exact in-memory connectivity for undirected graphs."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
rustc-hash.workspace = true

[lints]
workspace = true
