changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot[bot]
  categories:
    - title: "💥 Breaking Changes"
      labels:
        - "breaking-change"
        - "breaking"
    - title: "🚀 Features"
      labels:
        - "enhancement"
        - "feature"
    - title: "⚡ Performance Improvements"
      labels:
        - "performance"
        - "perf"
    - title: "🐛 Bug Fixes"
      labels:
        - "bug"
        - "fix"
    - title: "📚 Documentation"
      labels:
        - "documentation"
        - "docs"
    - title: "🧰 Maintenance & Dependencies"
      labels:
        - "dependencies"
        - "ci"
        - "maintenance"
